apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
data:
    client_id: ENC[AES256_GCM,data:Kr/gXB6LfIwQTCWjlZc0joufIcmwyQgz,iv:BWay/Vg8xiUUNR2EyUGNiuvsPY44516vjumKe5bMMhc=,tag:uSk2ijIbFdm4D+kApvRdTQ==,type:str]
    client_secret: ENC[AES256_GCM,data:4NL4SHKINFbDWu/ZiNfVZtmfeGOWqpvYOEB8HmFXwwDqGPDlw1EGcfIz8DdfY89wA0lFwDNvakwVOQsILkwJjC4dPwq3xTtBkPgjXqqjkjmPiDnaJ1Cu9w==,iv:IkKa1UgBRrJtbBXiI7ax9pDhjP4EZ4HCBH04Ginwtso=,tag:qHae9g4sDZLqckApo+FzEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-27T13:32:37Z"
    mac: ENC[AES256_GCM,data:bZugoILw9cF7T4Q0cpt1+yznPE/PaW8LJbRkGm77VUmlwixlrcMNlxJXnSqbMakrqPYyqnzK2Rrwid/ljmcIFg7pXiLQT9ifTJ684kjvARTvgBmY1NNpoU5nTOqUqTVLIWng4eh9ejtElmoC6PMyHeaFcTgZn0NzZDIzI58OY/E=,iv:Q64eWYJWqTVDkeW99x7MYrGggOooaGkwayM8FUB/Zsg=,tag:6RAUj1cC8gnrp89i/We+5A==,type:str]
    pgp:
        - created_at: "2024-08-27T13:32:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZUuW+SnyHPYSAQdAODS/rgg+4kh6KwWIzz+HHz8BVeucP6V+mBx2/Uus8DYw
            E3za06j3JiYgxD/q6RQFLZwh+kLntFO2A6VUTnOB8YpHZ+Kmk6lnZbOMlZivOOAb
            1GYBCQIQJ8j+NE6ttn+nFxYpUsNhlf7SE18l+dm3AaE2es8qR2+yUncdcn2rnlkg
            u7sBX/E9xrLRsnlgIjrZqQY0R034WiBkJqjuKYuAE+0qKJTXWD93XkvEU5amA3IO
            eoKyOvH31rU=
            =g7GQ
            -----END PGP MESSAGE-----
          fp: 06D3DBFB5FB5468467BA56529035F3A43D5001EA
        - created_at: "2024-08-27T13:32:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+Tj7GGlkPj7AQ/+KGbEUpiMXEL+7rPpwNf8VGgTZ6uv9rc1QxS+QyVBx4BV
            bKHvLG8lgpHEchLP+0IgzuxGw+u/4lxspTUZw5xjAkdsVHbcTxZwnLFffli5/d1Z
            6tb2054rfLzCGVnmx1Aa5fPhuz+9ViOzqKPlvzsgZyWah8bx04qdb6962rJ9ZHlJ
            RcqZVol26zFwr7pzqcN/mi+JtkdMnfZHilbBL5vaZtxnuEOM6dL76rOenShHHr+e
            5+3Zw1Fgxq52VSD7AtNEvRqTDbmlDHoQ3ojWW4YlIb5NdqyKHIpd9PNTvJumkhRx
            GMnuzkNyLNGYGFh/M0qfmyhaURCHZ6mAouAMVGV2vl8cCqRhuxqtAYncWBSu2I5+
            PxHLdeFKa86p3JzXdfxbFqVZg9zdy5GWvEvBUJnBSi8vieHXxkHzklDkXPifSESd
            knwFIVg68YQLhCcNrSEjKRdGs0E/vLCV4RdKTdB2T5Vwq6TzlFlGH8us6yrKUxOK
            ttzSlxdk/ZKTeQPqU8MFUDcwT0sno1j7CRD1/kQmnUMkc2Pc5rhubtTBuI8dPWNS
            aMhqwEImMSOtyWfDYYLcPe9y+KOffFcwjVX+HO2mCvZKEpYMSBnLvPak5MKTi4l4
            pITNx9CWDPlSEyvL43hJ90QL910298wCf87s6MrnNoe6q8xCGJ7gcY4kBzp74RbU
            ZgEJAhAMqGcY7sSsBK+v+H68UIlicLU0kiHBaZXnsh+tr9l4zKFBL/P6o9bMkkce
            hOU9RgZiM1JY9q5eAEORpDw3jFVDUYSPkt/qEfhzEh36jux/0ZestTHchOLwr7Ct
            7sDLQ8mAIg==
            =955d
            -----END PGP MESSAGE-----
          fp: 11C53C196E0848476A6BC5918D65584EF3DDF91B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
