---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 1m
  values:
    provider: dnsimple
    domainFilters:
      - run.terrible.systems
    env:
      - name: DNSIMPLE_OAUTH
        valueFrom:
          secretKeyRef:
            name: dnsimple-token
            key: token
      - name: DNSIMPLE_ACCOUNT_ID
        value: "106272"
      - name: DNSIMPLE_ZONES
        value: "terrible.systems"
