apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infra/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-dns
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
