apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: spin-operator
  namespace: spinkube
spec:
  interval: 5m0s
  url: oci://ghcr.io/spinkube/charts/spin-operator
  ref:
    tag: 0.2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spin-operator
  namespace: spinkube
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: spin-operator
    namespace: spinkube
  values:
